### ISSUE TITLE
How do you deploy the package?

### ISSUE THREAD

**Issue by core77** [davedew/afixia-theme-basic-bedrock#1]
... having the build folder in the theme folder and the scss folder within css.

Wouldn't it be cleaner to have the build stuff in the root folder? Than the clean package, which is ready to deploy could be in public/packages/theme_basic_bedrock.

I'm asking because I usually sync the packages to the live site.

What do you think?

**Comment by davedew** [comment]
Ya that works for me.  I'll make some changes.

**Comment by davedew** [comment]
Ok I made some changes, how does that work for you?

**Comment by core77** [comment]
Thanks! I'll take a closer look next week.

**Comment by core77** [comment]
I forked your repo and moved all the build related stuff to the root folder (ConcreteCMS is served from the 'public' folder).
If this is compatible to your workflow, I can open a pull request if you want.

Why did you comment out the BedrockThemeTrait? The Concrete docs say we need that...

**Comment by davedew** [comment]
Public folder is ok, but a lot of people don't use a composer install and upload directly to a cPanel type installation where everything is in public_html, so I feel like leaving the root folder undefined might be better for all users.  

You are right about the trait, I missed that in the docs.  I just added it back in.

**Comment by davedew** [comment]
Just a note, after adding the trait back in, I don't see Jquery being included (docs say: "Make sure your PageTheme class uses the BedrockThemeTrait This will register your theme as requiring jQuery and Font Awesome ").  

Maybe a bug, maybe it needs to be defined on install or I don't understand what else may be needed here.  If you add it via: $this->requireAsset('javascript', 'jquery'); this still works and Jquery starts working again.

**Comment by davedew** [comment]
Actually, I just followed that BedrockThemeTrait and all it does is the following, and because I'm using the asset system to register and include the app.js and app.css I need to provide the registerAssets in the page_theme.php so I had it right initially ;)

`trait BedrockThemeTrait
{

    public function registerAssets()
    {
        $this->requireAsset('font-awesome');
        $this->requireAsset('jquery');
        $this->requireAsset('vue');
        $this->requireAsset('bootstrap');
        $this->requireAsset('moment');
    }

    public function getThemeGridFrameworkHandle(): string
    {
        return 'bootstrap5';
    }

    public function getColorCollection(): ?ColorCollection
    {
        $factory = new ColorCollectionFactory();
        return $factory->createFromArray([
            'primary' => t('Primary'),
            'secondary' => t('Secondary'),
            'light' => t('Light'),
            'dark' => t('Dark'),
        ]);
    }
}`

**Comment by maschenborn** [comment]
I've installed a fresh copy concrete V9.0.1
copied folder 1 from your git into packages
copied folder 2 from your git to root
npm i in _build-folder
npx mix throws error: 
`ERROR in ../packages/theme_ssb/themes/ssb/css/scss/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import "~concretecms-bedrock/assets/bedrock/scss/frontend";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

**Comment by davedew** [comment]
Hmm I just created a new installation from scratch, cloned the repo moved the basic_bedrock_build folder to the root directory and placed the theme_basic_bedrock directory in the packages folder.  I then went to the basic_bedrock_build folder and ran npm i and then npx mix.  Everything complied correctly for me.  Is that the same folder structure you have?  Picture of my file structure attached
![Screenshot_20211124_105136](https://user-images.githubusercontent.com/3160839/143281537-f1d5f7be-6941-4126-a7b7-5f52dbe19b38.png)
.

**Comment by davedew** [comment]
Installation instructions added to the readme.

**Comment by core77** [comment]
@davedew I think there shouldn't be any SCSS file within packages/.../themes/... folder. SCSS files should be in "basic_bedrock_build" (or a subfolder of basic_bedrock_build).

**Comment by davedew** [comment]
Ya I'm good with that.  Might help people with directory issues too.

**Comment by davedew** [comment]
OK that change is in.

**Comment by core77** [comment]
Since there is no deployment question here any more I close this.
